framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(RABBITMQ_DSN)%'

            failed: 'doctrine://default?queue_name=failed'


        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Message\SendActivationMessage: async
            App\Message\SendPasswordRequest: async
            App\Message\SendPasswordConfirm: async

            # Route your messages to the transports
